name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
    tags:
      - '*'  # Trigger on any tag push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        # Set the image tag based on the Git tag or commit SHA
        IMAGE_TAG=${GITHUB_REF##*/}  # Get the tag or branch name
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          IMAGE_TAG=${IMAGE_TAG}  # Use the tag name
        else
          IMAGE_TAG=${GITHUB_SHA:0:7}  # Use the short commit SHA
        fi
        docker build -t munir131/httpgraviton:${IMAGE_TAG} .

    - name: Push Docker image
      run: |
        IMAGE_TAG=${GITHUB_REF##*/}  # Get the tag or branch name
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          IMAGE_TAG=${IMAGE_TAG}  # Use the tag name
        else
          IMAGE_TAG=${GITHUB_SHA:0:7}  # Use the short commit SHA
        fi
        docker push munir131/httpgraviton:${IMAGE_TAG} 